version: "3.9"
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    restart: unless-stopped
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:drop && bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dns_mapper
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
